services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./results:/usr/src/app/results
      - ./tests/postman/collections:/usr/src/app/tests/postman/collections
      - ./tests/postman/environments:/usr/src/app/tests/postman/environments
      - ./tests/postman/datafiles:/usr/src/app/tests/postman/datafiles
      - ./tests/bruno/collections-api:/usr/src/app/tests/bruno/collections-api
      - ./schedules:/usr/src/app/schedules
      - ./config:/usr/src/app/config
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
