services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./results:/usr/src/app/results
      - ./collections:/usr/src/app/collections
      - ./environments:/usr/src/app/environments
      - ./datafiles:/usr/src/app/datafiles
      - ./featuretests:/usr/src/app/featuretests
      - ./config:/usr/src/app/config
      - ./bruno:/usr/src/app/bruno
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
